# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_unibascostsurface.ui'
#
# Created: Tue Mar 26 01:05:01 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_UnibasCostSurface(object):
    def setupUi(self, UnibasCostSurface):
        UnibasCostSurface.setObjectName(_fromUtf8("UnibasCostSurface"))
        UnibasCostSurface.resize(685, 395)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UnibasCostSurface.sizePolicy().hasHeightForWidth())
        UnibasCostSurface.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(UnibasCostSurface)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblCostFile = QtGui.QLabel(UnibasCostSurface)
        self.lblCostFile.setObjectName(_fromUtf8("lblCostFile"))
        self.gridLayout.addWidget(self.lblCostFile, 11, 0, 1, 1)
        self.chkLoadAllocation = QtGui.QCheckBox(UnibasCostSurface)
        self.chkLoadAllocation.setEnabled(False)
        self.chkLoadAllocation.setChecked(True)
        self.chkLoadAllocation.setObjectName(_fromUtf8("chkLoadAllocation"))
        self.gridLayout.addWidget(self.chkLoadAllocation, 19, 0, 1, 2)
        self.chkAllocate = QtGui.QCheckBox(UnibasCostSurface)
        self.chkAllocate.setObjectName(_fromUtf8("chkAllocate"))
        self.gridLayout.addWidget(self.chkAllocate, 15, 0, 1, 2)
        self.lblIdField = QtGui.QLabel(UnibasCostSurface)
        self.lblIdField.setEnabled(False)
        self.lblIdField.setObjectName(_fromUtf8("lblIdField"))
        self.gridLayout.addWidget(self.lblIdField, 16, 0, 1, 1)
        self.chkLoadCost = QtGui.QCheckBox(UnibasCostSurface)
        self.chkLoadCost.setChecked(True)
        self.chkLoadCost.setObjectName(_fromUtf8("chkLoadCost"))
        self.gridLayout.addWidget(self.chkLoadCost, 13, 0, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lnCostFile = QtGui.QLineEdit(UnibasCostSurface)
        self.lnCostFile.setObjectName(_fromUtf8("lnCostFile"))
        self.horizontalLayout_2.addWidget(self.lnCostFile)
        self.btnBrowseCost = QtGui.QPushButton(UnibasCostSurface)
        self.btnBrowseCost.setObjectName(_fromUtf8("btnBrowseCost"))
        self.horizontalLayout_2.addWidget(self.btnBrowseCost)
        self.gridLayout.addLayout(self.horizontalLayout_2, 11, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lnAllocationFile = QtGui.QLineEdit(UnibasCostSurface)
        self.lnAllocationFile.setEnabled(False)
        self.lnAllocationFile.setObjectName(_fromUtf8("lnAllocationFile"))
        self.horizontalLayout_3.addWidget(self.lnAllocationFile)
        self.btnBrowseAllocation = QtGui.QPushButton(UnibasCostSurface)
        self.btnBrowseAllocation.setEnabled(False)
        self.btnBrowseAllocation.setObjectName(_fromUtf8("btnBrowseAllocation"))
        self.horizontalLayout_3.addWidget(self.btnBrowseAllocation)
        self.gridLayout.addLayout(self.horizontalLayout_3, 18, 1, 1, 1)
        self.cmbIdField = QtGui.QComboBox(UnibasCostSurface)
        self.cmbIdField.setEnabled(False)
        self.cmbIdField.setObjectName(_fromUtf8("cmbIdField"))
        self.gridLayout.addWidget(self.cmbIdField, 16, 1, 1, 1)
        self.cmbEntitiesLayer = QtGui.QComboBox(UnibasCostSurface)
        self.cmbEntitiesLayer.setObjectName(_fromUtf8("cmbEntitiesLayer"))
        self.gridLayout.addWidget(self.cmbEntitiesLayer, 0, 1, 1, 1)
        self.lblEntitiesLayer = QtGui.QLabel(UnibasCostSurface)
        self.lblEntitiesLayer.setObjectName(_fromUtf8("lblEntitiesLayer"))
        self.gridLayout.addWidget(self.lblEntitiesLayer, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 21, 1, 1, 1)
        self.lblAllocationFile = QtGui.QLabel(UnibasCostSurface)
        self.lblAllocationFile.setEnabled(False)
        self.lblAllocationFile.setObjectName(_fromUtf8("lblAllocationFile"))
        self.gridLayout.addWidget(self.lblAllocationFile, 18, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(UnibasCostSurface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout, 22, 1, 1, 1)
        self.cmbSurfaceRaster = QtGui.QComboBox(UnibasCostSurface)
        self.cmbSurfaceRaster.setObjectName(_fromUtf8("cmbSurfaceRaster"))
        self.gridLayout.addWidget(self.cmbSurfaceRaster, 4, 1, 1, 1)
        self.lblSurfaceRaster = QtGui.QLabel(UnibasCostSurface)
        self.lblSurfaceRaster.setObjectName(_fromUtf8("lblSurfaceRaster"))
        self.gridLayout.addWidget(self.lblSurfaceRaster, 4, 0, 1, 1)
        self.chkAllTouched = QtGui.QCheckBox(UnibasCostSurface)
        self.chkAllTouched.setObjectName(_fromUtf8("chkAllTouched"))
        self.gridLayout.addWidget(self.chkAllTouched, 3, 0, 1, 2)
        self.chkUseMemory = QtGui.QCheckBox(UnibasCostSurface)
        self.chkUseMemory.setObjectName(_fromUtf8("chkUseMemory"))
        self.gridLayout.addWidget(self.chkUseMemory, 20, 0, 1, 2)
        self.lblEntitiesMultipliers = QtGui.QLabel(UnibasCostSurface)
        self.lblEntitiesMultipliers.setEnabled(True)
        self.lblEntitiesMultipliers.setObjectName(_fromUtf8("lblEntitiesMultipliers"))
        self.gridLayout.addWidget(self.lblEntitiesMultipliers, 1, 0, 1, 1)
        self.cmbEntitiesMultipliers = QtGui.QComboBox(UnibasCostSurface)
        self.cmbEntitiesMultipliers.setEnabled(True)
        self.cmbEntitiesMultipliers.setObjectName(_fromUtf8("cmbEntitiesMultipliers"))
        self.gridLayout.addWidget(self.cmbEntitiesMultipliers, 1, 1, 1, 1)
        self.lblCostFile.setBuddy(self.lnCostFile)
        self.lblIdField.setBuddy(self.cmbIdField)
        self.lblEntitiesLayer.setBuddy(self.cmbEntitiesLayer)
        self.lblAllocationFile.setBuddy(self.lnAllocationFile)
        self.lblSurfaceRaster.setBuddy(self.cmbSurfaceRaster)
        self.lblEntitiesMultipliers.setBuddy(self.cmbEntitiesMultipliers)

        self.retranslateUi(UnibasCostSurface)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), UnibasCostSurface.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), UnibasCostSurface.reject)
        QtCore.QObject.connect(self.chkAllocate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lnAllocationFile.setEnabled)
        QtCore.QObject.connect(self.chkAllocate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.btnBrowseAllocation.setEnabled)
        QtCore.QObject.connect(self.chkAllocate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkLoadAllocation.setEnabled)
        QtCore.QObject.connect(self.chkAllocate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbIdField.setEnabled)
        QtCore.QObject.connect(self.chkAllocate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblIdField.setEnabled)
        QtCore.QObject.connect(self.chkAllocate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblEntitiesMultipliers.setEnabled)
        QtCore.QObject.connect(self.chkAllocate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblAllocationFile.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(UnibasCostSurface)
        UnibasCostSurface.setTabOrder(self.cmbEntitiesLayer, self.cmbEntitiesMultipliers)
        UnibasCostSurface.setTabOrder(self.cmbEntitiesMultipliers, self.chkAllTouched)
        UnibasCostSurface.setTabOrder(self.chkAllTouched, self.cmbSurfaceRaster)
        UnibasCostSurface.setTabOrder(self.cmbSurfaceRaster, self.lnCostFile)
        UnibasCostSurface.setTabOrder(self.lnCostFile, self.btnBrowseCost)
        UnibasCostSurface.setTabOrder(self.btnBrowseCost, self.chkLoadCost)
        UnibasCostSurface.setTabOrder(self.chkLoadCost, self.chkAllocate)
        UnibasCostSurface.setTabOrder(self.chkAllocate, self.cmbIdField)
        UnibasCostSurface.setTabOrder(self.cmbIdField, self.lnAllocationFile)
        UnibasCostSurface.setTabOrder(self.lnAllocationFile, self.btnBrowseAllocation)
        UnibasCostSurface.setTabOrder(self.btnBrowseAllocation, self.chkLoadAllocation)
        UnibasCostSurface.setTabOrder(self.chkLoadAllocation, self.chkUseMemory)
        UnibasCostSurface.setTabOrder(self.chkUseMemory, self.buttonBox)

    def retranslateUi(self, UnibasCostSurface):
        UnibasCostSurface.setWindowTitle(QtGui.QApplication.translate("UnibasCostSurface", "Unibas Cost Surface Analysis Tool v. 0.1, by D. Gnesi and D. Roubis", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCostFile.setText(QtGui.QApplication.translate("UnibasCostSurface", "Output cost surface raster:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkLoadAllocation.setText(QtGui.QApplication.translate("UnibasCostSurface", "Load the cost weighted allocation raster on the current project.", None, QtGui.QApplication.UnicodeUTF8))
        self.chkAllocate.setText(QtGui.QApplication.translate("UnibasCostSurface", "Perform a cost-based allocation analysis.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIdField.setText(QtGui.QApplication.translate("UnibasCostSurface", "ID field or band:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkLoadCost.setText(QtGui.QApplication.translate("UnibasCostSurface", "Load the cost surface raster on the current project.", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowseCost.setToolTip(QtGui.QApplication.translate("UnibasCostSurface", "browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowseCost.setText(QtGui.QApplication.translate("UnibasCostSurface", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowseAllocation.setToolTip(QtGui.QApplication.translate("UnibasCostSurface", "browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowseAllocation.setText(QtGui.QApplication.translate("UnibasCostSurface", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEntitiesLayer.setText(QtGui.QApplication.translate("UnibasCostSurface", "Entities layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAllocationFile.setText(QtGui.QApplication.translate("UnibasCostSurface", "Output allocation raster:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSurfaceRaster.setWhatsThis(QtGui.QApplication.translate("UnibasCostSurface", "<html><head/><body><p>You can select a raster band or an attribute field of the input layer containg float values that will be used to multiply the cost computed from those pixels or entities. A value of 1 will live the cost unaltered. With values &lt; 1, the cost will decrease. With values &gt; 1, the cost will encrease.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSurfaceRaster.setText(QtGui.QApplication.translate("UnibasCostSurface", "Friction surface layer (raster):", None, QtGui.QApplication.UnicodeUTF8))
        self.chkAllTouched.setText(QtGui.QApplication.translate("UnibasCostSurface", "Use the \'ALL_TOUCHED\' option while rasterizing the entities layer.", None, QtGui.QApplication.UnicodeUTF8))
        self.chkUseMemory.setText(QtGui.QApplication.translate("UnibasCostSurface", "Perform all calculations in memory.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEntitiesMultipliers.setText(QtGui.QApplication.translate("UnibasCostSurface", "Starting points\' rank field:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbEntitiesMultipliers.setWhatsThis(QtGui.QApplication.translate("UnibasCostSurface", "<html><head/><body><p>You can select a raster band or an attribute field of the input layer containg float values that will be used to multiply the cost computed from those pixels or entities. A value of 1 will live the cost unaltered. With values &lt; 1, the cost will decrease. With values &gt; 1, the cost will encrease.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

